import type { BadgeDef } from '../types/dictionary';

export const BADGE_DEFS: BadgeDef[] = [
  // ── Learning ────────────────────────────────────────────────────────────────
  {
    condition_key: 'first_lesson',
    name_th: 'นักเรียนใหม่',
    name_en: 'First Steps',
    description_th: 'เรียนจบบทแรก',
    icon: '🌱',
    category: 'learning',
    xp_reward: 50,
    condition_display: 'จบบทเรียนที่ 1',
  },
  {
    condition_key: 'three_lessons',
    name_th: 'นักเรียนขยัน',
    name_en: 'Diligent Student',
    description_th: 'เรียนจบ 3 บทเรียน',
    icon: '📚',
    category: 'learning',
    xp_reward: 30,
    condition_display: 'จบ 3 บทเรียน',
  },
  {
    condition_key: 'all_lessons',
    name_th: 'จบหลักสูตร',
    name_en: 'Graduate',
    description_th: 'เรียนจบทุกบทเรียน',
    icon: '🎓',
    category: 'learning',
    xp_reward: 100,
    condition_display: 'จบทุกบทเรียน',
  },

  // ── Quiz ────────────────────────────────────────────────────────────────────
  {
    condition_key: 'first_quiz',
    name_th: 'ตอบถูกครั้งแรก',
    name_en: 'First Answer',
    description_th: 'ทำ Quiz เป็นครั้งแรก',
    icon: '✅',
    category: 'quiz',
    xp_reward: 10,
    condition_display: 'ทำ Quiz ครั้งแรก',
  },
  {
    condition_key: 'first_perfect',
    name_th: 'เต็มร้อย',
    name_en: 'Perfect Score',
    description_th: 'ทำ Quiz ได้ 100% เป็นครั้งแรก',
    icon: '💯',
    category: 'quiz',
    xp_reward: 30,
    condition_display: 'Quiz 100% ครั้งแรก',
  },
  {
    condition_key: 'three_perfects',
    name_th: 'เต็มร้อย 3 ครั้ง',
    name_en: 'Triple Perfect',
    description_th: 'ทำ Quiz ได้ 100% จำนวน 3 ครั้ง',
    icon: '🌟',
    category: 'quiz',
    xp_reward: 50,
    condition_display: 'Quiz 100% จำนวน 3 ครั้ง',
  },

  // ── Streak ──────────────────────────────────────────────────────────────────
  {
    condition_key: 'streak_7',
    name_th: 'เริ่มต้นดี',
    name_en: 'Good Start',
    description_th: 'เรียนต่อเนื่อง 7 วัน',
    icon: '🔥',
    category: 'streak',
    xp_reward: 20,
    condition_display: 'Streak 7 วัน',
  },
  {
    condition_key: 'streak_14',
    name_th: 'สม่ำเสมอ',
    name_en: 'Consistent',
    description_th: 'เรียนต่อเนื่อง 14 วัน',
    icon: '⭐',
    category: 'streak',
    xp_reward: 30,
    condition_display: 'Streak 14 วัน',
  },
  {
    condition_key: 'streak_30',
    name_th: 'ไม่หยุดเรียน',
    name_en: 'Unstoppable',
    description_th: 'เรียนต่อเนื่อง 30 วัน',
    icon: '💎',
    category: 'streak',
    xp_reward: 50,
    condition_display: 'Streak 30 วัน',
  },
  {
    condition_key: 'streak_100',
    name_th: 'ตำนาน',
    name_en: 'Legend',
    description_th: 'เรียนต่อเนื่อง 100 วัน',
    icon: '👑',
    category: 'streak',
    xp_reward: 100,
    condition_display: 'Streak 100 วัน',
  },

  // ── Mastery ─────────────────────────────────────────────────────────────────
  {
    condition_key: 'mastered_10',
    name_th: 'จำได้แล้ว',
    name_en: 'Memory Spark',
    description_th: 'คำศัพท์ถึงระดับ mastered 10 คำ',
    icon: '🧠',
    category: 'mastery',
    xp_reward: 20,
    condition_display: 'Master 10 คำ',
  },
  {
    condition_key: 'mastered_30',
    name_th: 'คลังคำศัพท์',
    name_en: 'Vocabulary Vault',
    description_th: 'คำศัพท์ถึงระดับ mastered 30 คำ',
    icon: '📖',
    category: 'mastery',
    xp_reward: 30,
    condition_display: 'Master 30 คำ',
  },
  {
    condition_key: 'mastered_50',
    name_th: 'พจนานุกรมเดินได้',
    name_en: 'Walking Dictionary',
    description_th: 'คำศัพท์ถึงระดับ mastered 50 คำ',
    icon: '🏆',
    category: 'mastery',
    xp_reward: 50,
    condition_display: 'Master 50 คำ',
  },
];

export const TOTAL_BADGES = BADGE_DEFS.length; // 13
